trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: AzureCLI@2
  displayName: 'Clear Static website'
  inputs:
    azureSubscription: 'My Subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob delete-batch --account-name mystorageaccount --source "\$web"'
- task: AzureCLI@2
  displayName: 'Upload new Static Website'
  inputs:
    azureSubscription: 'My Subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name mystorageaccount --destination "\$web" --source ''$(Build.Repository.LocalPath)/dist/myappname'''

